import { Navbar, Footer } from "@/components";
import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Toaster } from "react-hot-toast";

const montserrat = Montserrat({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Toaster toastOptions={{ duration: 2000 }} />
        <Navbar />
        <main className="mx-auto min-h-[calc(100vh-82px)] max-w-7xl px-8 pt-20 xl:px-0">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
